
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'django-monolith'
    static_configs:
      - targets: ['django-monolith:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'fastapi-events'
    static_configs:
      - targets: ['fastapi-events:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'go-space'
    static_configs:
      - targets: ['go-space:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
